defaults-config: 'goal_sharing.yml'
synthesize-obs: true
synth-prop: 0.5
x-bounds: [-0.5, 0.5]
y-bounds: [0.2, 0.9]
z-bounds: [0.05, 0.5]
only-synth-tcp: false
synth-on-grid: true
synth-grid-size: 10
gt-hand-init-pos: true
synth-frame-stacking: false
# lr: 0.0003
# save-model: true
# num-epochs: 2000
# batch-size: 16
# train-split: 0.8
# skip-reward-training: false
# permute-types: false
# env: 'reach'
# use-shuffled: false
# num-rings: 5 #
# n: 100
# rand-n: false
# batch-reward-computation: true
# scale-rewards: true
# include-actions: false
# synth-edges-only: false
# only-synthetic: false
# demonstration-type: 'normal'
# shuffle: true
# extra-success-reward: 5.0 # maybe move to model config later