num-envs: 16
learning-steps: 10000000
algorithm: 'SAC'
gamma: 0.99
learning-rate: 0.0001
render-interval: 100000
render-duration: -1
policy-latent-dim: 512
policy-num-layers: 2
num-critics: 2
target-update-interval: 1
train-frequency: 1
use-sde: true
batch-size: 5000
save-freq: 100000
weight-resets: false
weight-reset-interval: 1000000
weight-reset-ratio: 0.5
gradient-steps: 1
replay-buffer-size: 10000000
load-run: null
num-inference-goals: -1
gpu-state-encoder: true
use-goal: null
render-reward: true
unscale-rewards: false
offline-rl: false
offline-dataset: null
offline-num-task-reps-per-obs: 1
offline-num-transitions: 1000000
offline-rejection-sampling-num-bins: 10
offline-rejection-sampling-bias-factor: 1.1
offline-training-epochs: 100
use-gt-reward: false
scale-gt-reward: false
use-gt-goal: false
no-task-rep: false
num-discrete-reward-bins: null
proximity-reward: 0.0
extra-success-reward: 5.0
no-init-success: false
success-requires-touch: false
full-legacy: false
full-legacy-reinit-goals: true
ppo-n-steps: 2048
third-gt: false
half-gt: false
ensembling: null # options: 'mean', 'median', 'min', 'random'
grasp-rew-only: false